git submodule update --init --recursive

cp glibc_244/bullet3_CMakeLists.txt bullet3/CMakeLists.txt

cmake -S "bullet3" -B "bullet3/build" -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -DBUILD_SHARED_LIBS=FALSE -DUSE_GLUT=FALSE -DUSE_GRAPHICAL_BENCHMARK=FALSE -DBUILD_BULLET2_DEMOS=FALSE -DBUILD_BULLET_ROBOTICS_EXTRA=FALSE -DBUILD_BULLET_ROBOTICS_GUI_EXTRA=FALSE  -DBUILD_BULLET_EXTRAS=FALSE -DBUILD_CLSOCKET=FALSE -DBUILD_EXTRAS=FALSE -DBUILD_CPU_DEMOS=FALSE -DBUILD_EGL=FALSE -DBUILD_GIMPACTUTILS_EXTRA=FALSE -DBUILD_HACD_EXTRA=FALSE -DBUILD_INVERSE_DYNAMIC_EXTRA=FALSE -DBUILD_OBJ2SDF=FALSE -DBUILD_OBJ2SDF_EXTRA=FALSE -DBUILD_SERIALIZE_EXTRA=FALSE -DBUILD_ENET=FALSE -DBUILD_OPENGL3_DEMOS=FALSE -DBUILD_UNIT_TESTS=FALSE -DENABLE_VHACD=FALSE -DINSTALL_EXTRA_LIBS=FALSE -DINSTALL_CMAKE_FILES=FALSE -DUSE_SOFT_BODY_MULTI_BODY_DYNAMICS_WORLD=FALSE -DCONVEX_DECOMPOSITION_EXTRA=FALSE -DINSTALL_LIBS=TRUE -DLINK_AGAINST_OLDER_GLIBC=TRUE

cd bullet3/build

make OPT=opt install

cd ../../

cp glibc_244/capstone_CMakeLists.txt capstone/CMakeLists.txt

cmake -S "capstone" -B "capstone/build" -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_C_FLAGS=-m32 -DCAPSTONE_ARCHITECTURE_DEFAULT=FALSE -DCAPSTONE_ARM64_SUPPORT=FALSE -DCAPSTONE_ARM_SUPPORT=FALSE -DCAPSTONE_BUILD_CSTOOL=FALSE -DCAPSTONE_BUILD_SHARED=FALSE -DCAPSTONE_BUILD_STATIC=TRUE -DCAPSTONE_BUILD_TESTS=FALSE -DCAPSTONE_EVM_SUPPORT=FALSE -DCAPSTONE_INSTALL=TRUE -DCAPSTONE_M680X_SUPPORT=FALSE -DCAPSTONE_M68K_SUPPORT=FALSE -DCAPSTONE_MIPS_SUPPORT=FALSE -DCAPSTONE_MOS65XX_SUPPORT=FALSE -DCAPSTONE_OSXKERNEL_SUPPORT=FALSE -DCAPSTONE_PPC_SUPPORT=FALSE -DCAPSTONE_SPARC_SUPPORT=FALSE -DCAPSTONE_SYSZ_SUPPORT=FALSE -DCAPSTONE_TMS320C64X_SUPPORT=FALSE -DCAPSTONE_XCORE_SUPPORT=FALSE -DCAPSTONE_X86_SUPPORT=TRUE -DCMAKE_INSTALL_PREFIX=capstone/build -DLINK_AGAINST_OLDER_GLIBC=TRUE

cd capstone/build

make OPT=opt install

strings capstone/build/lib/libcapstone.a | grep GLIBC

cd ../../

make OPT=opt install