# Since this file is under CVS control and we cannot store
# symbolic links in CVS (and neither under Windows) we
# include the Makefile from the metamod directory instead
# of linking to it.

include ../metamod/Makefile

INCLUDEDIRS+=-I$(SDKSRC)/../CDetour -I$(SDKSRC)/../libudis86 -I$(SDKSRC)/../bullet3/src