if(NOT DEFINED FORMAT_VALIDATION_SOURCE_PATH)
    set(FORMAT_VALIDATION_SOURCE_PATH "$ENV{FORMAT_VALIDATION_SOURCE_PATH}" CACHE PATH "Shared format tooling")
endif()
if(NOT FORMAT_VALIDATION_SOURCE_PATH)
    set(FORMAT_VALIDATION_SOURCE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/FormatValidation")
endif()
get_filename_component(FORMAT_VALIDATION_SOURCE_PATH "${FORMAT_VALIDATION_SOURCE_PATH}"
    ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
foreach(file .clang-format clang-format-validate.py cmake/FormatValidation.cmake)
    if(NOT EXISTS "${FORMAT_VALIDATION_SOURCE_PATH}/${file}")
        message(FATAL_ERROR "FORMAT_VALIDATION_SOURCE_PATH is missing ${file}; initialize submodules.")
    endif()
endforeach()
include("${FORMAT_VALIDATION_SOURCE_PATH}/cmake/FormatValidation.cmake")
configure_file("${FORMAT_VALIDATION_SOURCE_PATH}/.clang-format" "${CMAKE_CURRENT_SOURCE_DIR}/.clang-format" COPYONLY)
add_custom_target(format-check)
add_custom_target(format)
foreach(component IN LISTS MMFG_COMPONENTS)
    format_validation_add_component("${component}" "${CMAKE_CURRENT_SOURCE_DIR}/${component}")
    add_dependencies(format-check "${component}-format-check")
    add_dependencies(format "${component}-format")
endforeach()
