name: ubuntu

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        config: [Debug, Release]
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false
      
      - name: Install build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential gcc gcc-multilib g++-multilib
      
      - name: Build all
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cmake -S . -B build-cmake/native -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          cmake --build build-cmake/native --parallel 6
          cmake --install build-cmake/native --prefix build

      - name: Archive the build directory
        if: matrix.config == 'Release'
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'metamod-fallguys-ubuntu-i386.zip'
          path: 'build'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') && matrix.config == 'Release'
        with:
          name: metamod-fallguys-${{ github.ref }}
          files: |
            metamod-fallguys-ubuntu-i386.zip
